// ─── BUSINESS BUILDER DATA ────────────────────────────────────
// All ProductIQ content lives here.
// Phase 1 questions are static.
// Phase 2 questions are generated by Claude API based on answers.
// Phase 3 results are generated by Claude API.

export const productIQData = {
  title: 'ProductIQ',
  subtitle: 'What should you build?',
  description:
    'Answer 8 questions about your business. Get a personalised product strategy — platform recommendation, name ideas, monetisation roadmap, and your first 3 things to build.',
  pageTitle: 'ProductIQ — What should you build?',
  pageDescription:
    'Free AI-powered business product strategy tool. Answer 8 questions and get a personalised recommendation for your online presence — platform, name, monetisation, and first steps.',
}

export const phase1Questions = [
  {
    id: 'business',
    number: 1,
    question: 'Describe your business in one or two sentences.',
    hint: 'What do you sell or do? Where are you based? The more specific, the better your strategy.',
    type: 'textarea',
    placeholder: 'e.g. I repair phones and sell accessories in Lagos. Most customers come through walk-ins and WhatsApp referrals.',
    options: [],
  },
  {
    id: 'customers',
    number: 2,
    question: 'Who are your main customers?',
    hint: 'Think about who actually pays you money today.',
    type: 'options',
    placeholder: 'Or describe your customer in your own words...',
    options: [
      'Individuals / everyday consumers',
      'Small business owners',
      'Young professionals (20s–30s)',
      'Parents and families',
      'Students',
      'Other businesses (B2B)',
    ],
  },
  {
    id: 'problem',
    question: "What's the #1 thing holding your business back right now?",
    number: 3,
    hint: 'Be honest — the more specific you are, the better your strategy will be.',
    type: 'options',
    placeholder: 'Or describe your problem in your own words...',
    options: [
      'Nobody knows I exist online',
      'I lose customers to competitors',
      'Managing customers is chaotic',
      "I can't take payments online",
      'I have no way to show my work',
      'I rely too much on referrals',
    ],
  },
  {
    id: 'goal',
    number: 4,
    question: 'What do you most want to achieve in the next 6 months?',
    hint: 'Pick the outcome that would make the biggest difference to your business.',
    type: 'options',
    placeholder: 'Or describe your goal...',
    options: [
      'Get more customers finding me online',
      'Sell products or services directly online',
      'Look more professional and trustworthy',
      'Manage bookings or appointments better',
      'Build a loyal customer base',
      'Grow beyond my current location',
    ],
  },
  {
    id: 'current-tools',
    number: 5,
    question: 'How do you currently run your business day-to-day?',
    hint: 'What tools or methods do you use to talk to customers, take orders, or get paid?',
    type: 'options',
    placeholder: 'Or describe how you currently operate...',
    options: [
      'WhatsApp for everything',
      'Instagram DMs and posts',
      'Word of mouth only',
      'Phone calls and SMS',
      'A basic website already exists',
      'Physical shop / walk-ins only',
    ],
  },
  {
    id: 'competitors',
    number: 6,
    question: 'Do your competitors have an online presence?',
    hint: "This tells us how urgent your situation is and what you're up against.",
    type: 'options',
    placeholder: 'Or describe what you know about your competitors...',
    options: [
      'Yes — and they get customers because of it',
      'Some do, some don\'t',
      'No — I\'d be first in my area',
      "I don't know who my competitors are",
      'I have no direct competitors',
    ],
  },
  {
    id: 'budget',
    number: 7,
    question: 'What is your budget for building your online presence?',
    hint: "Be realistic — there's a right approach for every budget.",
    type: 'options',
    placeholder: 'Or describe your budget situation...',
    options: [
      'Free tools only — no budget right now',
      'Under ₦50,000',
      '₦50,000 – ₦150,000',
      '₦150,000 – ₦500,000',
      '₦500,000+',
      'Budget is flexible for the right solution',
    ],
  },
  {
    id: 'timeline',
    number: 8,
    question: 'When do you want this live?',
    hint: 'This shapes how we prioritise what to build first.',
    type: 'options',
    placeholder: 'Or describe your timeline...',
    options: [
      'As soon as possible — this week',
      'Within the next month',
      'In the next 3 months',
      'No rush — I want it done right',
      "I'm still exploring options",
    ],
  },
]

export const attahVoiceContext = `
You are generating content for a web tool called ProductIQ on attah.dev — the portfolio of Attah Kelechi, a Frontend Engineer and product strategist based in Nigeria.

The person reading these results IS the business owner who just answered the questions. Speak DIRECTLY to them using "you" and "your" — never "they", "them", or "the business owner".

Attah's voice and values:
- Direct and practical, never theoretical
- Genuinely cares about small business growth, not just billing clients
- Tells clients what's good AND bad for their business honestly
- Believes the first thing any business needs is social media (LinkedIn, Instagram, WhatsApp) plus a website
- Hates when developers overcharge small businesses or build unnecessarily complex solutions
- Puts everything into projects and wants to be part of the growth process
- Warm, confident, Nigerian context — understands the local market deeply
- Speaks plainly, no jargon
- References specific things the client said, not generic advice

CRITICAL RULES:
- Always say "you" and "your business" — NEVER "they", "them", "the business", "the client", or "the owner"
- Wrong: "This platform is right for them because..."
- Right: "This platform is right for you because..."
- Wrong: "The business should focus on..."
- Right: "You should focus on..."
- The attahNote must be written as Attah speaking directly to the client — warm, personal, specific
`

export const phase2SystemPrompt = (answers: Record<string, string>) => `
${attahVoiceContext}

A potential client has just completed 8 foundation questions. Here are their answers:
${Object.entries(answers).map(([k, v]) => `- ${k}: ${v}`).join('\n')}

Generate exactly 3 follow-up questions in JSON format. These should:
1. Be specific to THIS person's situation — reference what they told you
2. Uncover information that would change the product recommendation
3. Feel like questions a smart consultant would ask after reading their answers
4. Be conversational — start with a brief observation about their answer before asking

Return ONLY valid JSON in this exact format, no other text:
{
  "questions": [
    {
      "id": "followup_1",
      "observation": "Brief 1-2 sentence observation about what they said that leads into this question",
      "question": "The actual follow-up question",
      "options": ["Option 1", "Option 2", "Option 3", "Option 4"],
      "placeholder": "Or tell me in your own words..."
    },
    {
      "id": "followup_2",
      "observation": "...",
      "question": "...",
      "options": ["...", "...", "...", "..."],
      "placeholder": "..."
    },
    {
      "id": "followup_3",
      "observation": "...",
      "question": "...",
      "options": ["...", "...", "...", "..."],
      "placeholder": "..."
    }
  ]
}
`

export const resultsSystemPrompt = (allAnswers: Record<string, string>) => `
${attahVoiceContext}

A potential client has completed all questions. Here are ALL their answers:
${Object.entries(allAnswers).map(([k, v]) => `- ${k}: ${v}`).join('\n')}

Generate a complete product strategy in JSON format. Be VERY specific to their situation.
For the personal note — write in first person as Attah. Reference specific things they told you.
Make the strategy feel like only YOU can execute it — not generic advice anyone could follow.
The "unfair advantage" should reveal something about their situation they may not have consciously noticed.

Return ONLY valid JSON, no other text:
{
  "businessName": {
    "recommended": "Primary name recommendation",
    "alternatives": ["Alternative 1", "Alternative 2"],
    "reasoning": "2-3 sentences explaining why this name works for their specific situation"
  },
  "platform": {
    "recommendation": "What to build (e.g. Simple booking website + WhatsApp integration)",
    "reasoning": "Why this is right for them",
    "developerMistake": "What most developers would get wrong for this specific business"
  },
  "monetisation": [
    { "period": "Month 1", "action": "Specific monetisation action" },
    { "period": "Month 3", "action": "Specific monetisation action" },
    { "period": "Month 6", "action": "Specific monetisation action" }
  ],
  "firstThreeToBuild": [
    { "number": "01", "title": "Thing to build", "description": "Why this first and what it does" },
    { "number": "02", "title": "Thing to build", "description": "Why second and what it does" },
    { "number": "03", "title": "Thing to build", "description": "Why third and what it does" }
  ],
  "unfairAdvantage": "A 1-2 sentence insight about what they already have that most businesses don't — pulled from their specific answers. Should feel like a revelation.",
  "attahNote": "A personal note from Attah in first person. 3-4 sentences. Reference specific things they told you. End with what you'd do first and why. Sound like yourself — warm, direct, Nigerian context, growth-focused. Make them feel like you're the only one who truly understood their situation."
}
`